/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rules;

import Menu.MenuGui;
import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author BATMAN
 */
public class RulesGui extends javax.swing.JFrame {

    /**
     * Creates new form ObjectGui
     */
    public RulesGui() {
        initComponents();
        jButton1.setText("Go Back!");
        
        for(int i=0; i<20; i++){
            JTextArea area = new JTextArea();
            area.setBackground(Color.LIGHT_GRAY);
            area.setEditable(false);
            switch(i){
                case 0:
                    area.setText("The object of the game is to become the wealthiest player through buying, renting, and trading Property with the intention of bankrupting all opponents.");
                    jTabbedPane1.addTab("Object", null, area, "Object");
                    break;
                case 1:
                    area.setText("The equipment consists of a board, 2 dice, tokens, 32 Houses and 12 Hotels (set aside extras), 16 Chance and 16 Community Chest cards, 28 Title Deed cards (one for each property), and $20,580 play money (thirty of each bill denomination).");
                    jTabbedPane1.addTab("Equipment", null, area, "Equipment");
                    break;
                case 2: 
                    area.setText("Place the board on a table and put the Chance and Community Chest cards face down on their allotted spaces of the board. Each player chooses one token to represent them while travelling around the board. Each player is given $1500 divided as follows:\n\nU.S. editions prior to 2008 U.S. editions since 2008 / British editions\n2 × $500\t2 × $/£500\n2 × $100\t4 × $/£100\n2 × $50\t1 × $/£50\n6 × $20\t1 × $/£20\n5 × $10\t2 × $/£10\n5 × $5\t1 × $/£5\n5 × $1\t5 × $/£1\n\nAll remaining money and other equipment go to The Bank.");
                    jTabbedPane1.addTab("Preparation", null, area, "Preparation");
                    break;
                case 3:
                    area.setText("Select as Banker a player who will also make a good Auctioneer. A Banker who plays in the game must keep their personal assets separate from those of the Bank. When more than five persons play, the Banker may elect to act only as Banker/Auctioneer.");
                    jTabbedPane1.addTab("Banker", null, area, "Banker");
                    break;
                case 4:    
            }
        }                                                             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jButton1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        MenuGui menu = new MenuGui();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RulesGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RulesGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RulesGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RulesGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RulesGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
